#!/bin/sh

case "$1" in
  start|restart)
	. /opt/easyVpn/etc/settings
	if [ "$1" = "restart" ]; then
	    echo -n "Restarting module easyVpn: "
	    killall easyVpnd 2> /dev/null
	else
	    echo -n "Starting module easyVpn: "
	fi
	if [ "$MOD_EASYVPN_ENABLED" != "1" ]; then
	    echo "skipped"
	    exit 0
	fi
	/opt/easyVpn/etc/conf2vpnc
	/opt/easyVpn/bin/easyVpnd &
	RETVAL=$?
	if [ $RETVAL = 0 ]; then echo "done"; else echo "failed"; fi
	exit $RETVAL
	;;
  stop)
	echo -n "Stopping module easyVpn: "
	killall easyVpnd 2> /dev/null
	RETVAL=$?
	rm -r /var/run/vpnc/vpnc.conf
	if [ $RETVAL = 0 ]; then echo "done"; else echo "failed"; fi
	exit $RETVAL
	;;
  status)
	echo -n "Module easyVpn is "
	killall -0 easyVpnd 2> /dev/null
	RETVAL=$?
	if [ $RETVAL = 0 ]; then echo "running"; else echo "stopped"; fi
	exit $RETVAL
	;;
  defaults)
	cp /opt/easyVpn/etc/defaults /opt/easyVpn/etc/settings 2> /dev/null
	;;
  *)
	echo "Usage: $0 {start|stop|restart|status|defaults}"
	exit 1
esac
